name: xeus-cling
channels:
  - conda-forge
dependencies:
  - xeus-cling=0.15.0
  - xtensor=0.24.4
  - xtensor-blas=0.20.0
  - libstdcxx-devel_linux-64=*=*19
  - gcc=13.2
  - pip
  - pip:
    - jupyter-cpp-kernel>=1.0.0a8
